services:
  bot:
    build: .
    container_name: natk-schedule-bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  postgres:
    image: postgres:16.9
    container_name: postgres-natk
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata

volumes:
  pg_data:
    driver: local

networks:
  my-network:
    driver: bridge
