# EDIT IT FOR RUN ON YOUR OWN MACHINE!
database.driver=org.postgresql.Driver
database.dialect=org.hibernate.dialect.PostgreSQLDialect

# SENSITIVE (SECRET IN PRODUCTION) DATA!
database.url=jdbc:postgresql://127.0.0.1:5432/natk_schedule
database.username=postgres
database.password=postgres

database.show_sql=true
database.format_sql=true

database.hbm2ddl=update